### ISSUE TITLE
Better description in README

### ISSUE THREAD

**Issue by palash25** [debck/car-CLI#1]
I don't really understand this tool. You have mentioned the commands but not the output of those commands.

An example output of at least one command would be a nice addition to the README or maybe you can add a gif take a look at https://github.com/phw/peek

**Comment by debck** [comment]
Sure will improve it.
Thnx.

**Comment by debck** [comment]
Just updated something 
feedback ?

**Comment by debck** [comment]
I think this small project has not much functionality. Though i improved the description little.
so, closing this issue 
Thnx .
