### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by palash25** [debck/car-CLI#2]
Tested code is reliable code

This is an important skill better to learn testing now it will help you in ways you cannot even imagine and especially with re: open source dev

There are several frameworks but you might wanna check this out as a starting point https://github.com/facebook/jest

**Comment by debck** [comment]
Thnx bhaiya  ...will check it too ...

**Comment by debck** [comment]
I just added some tests.
Got some idea on writing tests .
thnx @palash25
